stages:
  - clean
  - package
  - build-images
  - push-images

clean:
  stage: clean
  tags:
    - mixeway
  script:
    - mvn clean
  only:
    - master


package:
  stage: package
  tags:
    - mixeway
  script:
    - mvn install -DskipTests
  only:
    - master

build-images:
  stage: build-images
  tags:
    - mixeway
  script:
    - mvn package -DskipTests
    - docker build -t ci-docker.corpnet.pl/mixewaytesting/scanner:latest --build-arg HTTPS_PROXY=$HTTPS_PROXY --build-arg HTTP_PROXY=$HTTP_PROXY --build-arg NO_PROXY=$NO_PROXY .
    - docker tag ci-docker.corpnet.pl/mixewaytesting/scanner:latest ci-docker.corpnet.pl/library/mixewaytesting/scanner:latest
    - docker tag ci-docker.corpnet.pl/mixewaytesting/scanner:latest registry.d00b.pl/mixeway/mixewaytesting:latest
    - docker tag registry.d00b.pl/mixeway/mixewaytesting:latest d4i-harbor.corpnet.pl/mixeway/mixewaytesting:latest
    - docker images ls
  only:
    - master

push-images:
  stage: push-images
  tags:
    - mixeway
  script:
    - echo "pushing"
  only:
    - master
