stages:
  - clean
  - package
  - build-image-csci
  - build-image-dop
  - build-image-cs
  - push-images

clean:
  stage: clean
  tags:
    - mixeway
  script:
    - mvn clean
  only:
    - master


package:
  stage: package
  tags:
    - mixeway
  script:
    - mvn install -DskipTests
  only:
    - master

build-image-csci:
  stage: build-image-csci
  tags:
    - mixeway
  script:
    - docker build --no-cache -t ci-docker.corpnet.pl/mixewaytesting/scanner:latest --build-arg HTTPS_PROXY=$HTTPS_PROXY --build-arg HTTP_PROXY=$HTTP_PROXY --build-arg NO_PROXY=$NO_PROXY .
  only:
    - master
build-image-dop:
  stage: build-image-dop
  tags:
    - mixeway
  script:
    - docker build . -t ci-docker.corpnet.pl/mixewaytesting/scanner:latest
  only:
    - master
build-image-cs:
  stage: build-image-cs
  tags:
    - mixeway
  script:
    - docker build . -t ci-docker.corpnet.pl/mixewaytesting/scanner:latest
  only:
    - master
push-images:
  stage: push-images
  tags:
    - mixeway
  script:
    - docker build . -t ci-docker.corpnet.pl/mixewaytesting/scanner:latest
  only:
    - master
